### ISSUE TITLE
arm64 not supported

### ISSUE THREAD

**Issue by heefan** [biasedbit/curl-ios-build-scripts#24]
Hi,

I tried to build for iOS7.1 with the following command
`./build_curl   --archs arm7,arm7s,arm64`

However, it always failed like this,

> [COMPILE]  WARN - Configuration for architecture 'arm64' failed.
> [ BUILD ] ERROR - Compilation failed for all requested architectures.

If I run the `build_curl`the script by default, it build for `arm7` and `arm7s` only.

Do I miss some information? 

Thanks & Regards

**Comment by swallow19851009** [comment]
I have tried to compile with xcode 6.1 & ios-dev version in curl.

it works well for building and running to device.

but when trying to archive product, I got error below.

"__curl_rule_01__ declared as array" with a negative size.

so I have removed arm64 in architecture setting.

error is removed. but I don't know the way for arm64.

**Comment by treasurebox** [comment]
This is because curlbuild.h differs for the 32 bit and 64 bit versions, but the build script assumes that they are the same, and uses just the 32 bit version.
One can merge them with simple ifdefs manually, or if someone has the time the build script could be extended to handle this.

**Comment by jonnyijapan** [comment]
Sorry to bump, but this isn't going to get fixed or do we look somewhere else?
